# C2DL Docker Environment
# DEV-Environment only
#
# Copyright 2021-2025 CCDirectLink

# noinspection SpellCheckingInspection
services:

  # Database: MariaDB
  db:
    container_name: "c2dl-mariadb"
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-c2dl}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-c2dl}
      MARIADB_USER: ${MARIADB_USER:-c2dl}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-c2dl}
    ports:
      - '3306:3306'
    volumes:
      - ./.run/mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - back

  # Adminer
  adminer:
    container_name: "c2dl-adminer"
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - back
      - front

  # PHP
  php:
    container_name: "c2dl-php"
    restart: always
    build:
      context: ..
      dockerfile: ./docker/conf/php/Dockerfile
    volumes_from:
      - apache
    volumes:
      - ./conf/php/php.ini:/usr/local/etc/php/conf.d/user-php.ini
    working_dir: /usr/local/apache2/htdocs
    ports:
      - "9000:9000"
    networks:
      - back

  # Apache
  apache:
    container_name: "c2dl-apache"
    image: httpd:2.4
    restart: always
    volumes:
      - ./.run/logs:/usr/local/apache2/logs
      - ./conf/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./conf/apache/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - ../src/c2dl:/usr/local/apache2/htdocs
      - ./servertest:/usr/local/apache2/servertest
    depends_on:
      - db
      - node
    working_dir: /usr/local/apache2/htdocs
    ports:
      - 8088:80
      - 8888:8888
    networks:
      - back
      - front

  # Node
  node:
    container_name: "c2dl-node"
    image: node:current-bookworm-slim
    command: sh -c "npm install && npm run build"
    healthcheck:
      test: [ "CMD-SHELL", 'bash -c "[ -d node_modules ]"' ]
      interval: 45s
      timeout: 10s
      retries: 4
    volumes:
      - ../src/c2dl:/c2dl
    working_dir: /c2dl

networks:
  front:
    driver: bridge
  back:
    driver: bridge
